[package]
name = "payments-engine"
version = "0.1.0"
authors = ["runner"]
edition = "2018"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = { version = "1.0.130", features = ["derive"] }
